### ISSUE TITLE
Release 2.30 not triggered

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/KiSAO#102]
Not sure what went wrong, but it seems the release for the tag `2.30` was not triggered. I followed the instructions, but somehow this did not work.

See:
https://github.com/SED-ML/KiSAO/actions/runs/1323847111

@jonrkarr Could you release the `2.30` package?

**Comment by jonrkarr** [comment]
This is because the tag was different than the head of the dev branch. I'll delete the tag and add it again. 

FYI, KiSAO is not updating in OLS. The migration of KISAO to github still hasn't fully propagated through the chain of sources (OBO foundry) that OLS relies on.

**Comment by matthiaskoenig** [comment]
I already took care of the OLS issues (see https://github.com/SED-ML/KiSAO/issues/103). Should be fixed soon.

**Comment by jonrkarr** [comment]
Done
