### ISSUE TITLE
Clarify math functions as to whether to ignore NaN

### ISSUE THREAD

**Issue by luciansmith** [SED-ML/KiSAO#94]
The new dimension-reducing functions min/max/mean/etc. do not say whether to ignore NaN values.  In theory, KiSAO could define a term for both versions (ignore/don't ignore), but at the least, the existing functions should clarify which version they are (and I vote for the 'ignore' version).

cf https://github.com/SED-ML/sed-ml/issues/56

**Comment by jonrkarr** [comment]
Agreed. For concreteness, the existing terms could be implemented using NumPy `nanmean`, etc.

**Comment by luciansmith** [comment]
Specified existing functions to ignore NaN, https://github.com/SED-ML/KiSAO/pull/95

**Comment by jonrkarr** [comment]
Closed by #95
