### ISSUE TITLE
labels of systems properties should be lowercase

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/KiSAO#99]
All labels start with lowercase in the KISAO ontology with exception of the newly added `systems property` children
https://bioportal.bioontology.org/ontologies/KISAO/?p=classes&conceptid=http%3A%2F%2Fwww.biomodels.net%2Fkisao%2FKISAO%23_KISAO_0000800

All labels of children should be lowercase with exception of `Jacobian matrix`, `L0 matrix` and `Nr matrix`.

**Comment by jonrkarr** [comment]
KiSAO wasn't set up with this requirement.

**Comment by matthiaskoenig** [comment]
Yes, but it would still be great if we could be as consistent as possible, especially for the new terms added.

**Comment by jonrkarr** [comment]
These are the terms that @luciansmith added.

I agree, but I wouldn't consider this a bug. This is a request for an additional constraint and corresponding validation.

**Comment by luciansmith** [comment]
I'm more than happy to modify things.  I was sort of blundering my way through adding the new terms ;-)

**Comment by jonrkarr** [comment]
Corrected in 2.21. Will be released to GitHub/Bioportal/PyPI soon.

Note, OLS still displays an older version. This will be updated when updates are propagated from OBO foundry. Not sure what that timeline is.
